# Learn more about configuring your app at https://shopify.dev/docs/apps/tools/cli/configuration

client_id = "db3a710f6c200ebd99df5a58736571d7"
name = "uto-g2-a"
application_url = "https://studying-plaza-radical-engines.trycloudflare.com"
embedded = true

[build]
automatically_update_urls_on_dev = true
dev_store_url = "test-api-mn.myshopify.com"

[access_scopes]
# Learn more at https://shopify.dev/docs/apps/tools/cli/configuration#access_scopes
scopes = "write_products,read_products"

[auth]
redirect_urls = [
  "https://studying-plaza-radical-engines.trycloudflare.com/auth/callback",
  "https://studying-plaza-radical-engines.trycloudflare.com/auth/shopify/callback",
  "https://studying-plaza-radical-engines.trycloudflare.com/api/auth/callback"
]

[webhooks]
api_version = "2024-01"

[pos]
embedded = false
